### ISSUE TITLE
Error in Custom Plugin doesn't return Exit Code

### ISSUE THREAD

**Issue by esauser** [tsqllint/tsqllint#203]
Great news!  I have successfully created my own custom plugin and integrated into our pipeline.  Bad news... when it fails, and exist code isn't returned.  That last `0` is the exit code at that point.
![image](https://user-images.githubusercontent.com/24945592/50032866-d3ab8280-ffbb-11e8-9572-4a02292d2e48.png)

**Comment by esauser** [comment]
There are actually a lot of scenarios where an exit code of `0` is returned when it is not expected.  See the following:
![image](https://user-images.githubusercontent.com/24945592/50039159-c958ab00-fff2-11e8-9486-ad22bb21df59.png)

![image](https://user-images.githubusercontent.com/24945592/50039186-39673100-fff3-11e8-8870-49f2d4203eab.png)

**Comment by nathan-boyd** [comment]
Our plugin implementation is purposefully naive. The core application passes an IPluginContext, and an IReporter, and expects nothing in return. There is no way to pass messages back or inform the calling application that something should happen, such as set the exit code. That needs to be handled from within the plugin. You can count on TSQLLint to not stomp on your exit code, for example setting it to zero when you've set it to non-zero, but that is it.

**Comment by esauser** [comment]
I can confirm that manually setting the exist code within the plugin handles two of the cases above, but the invalid JSON has nothing to do with a plugin and is not something that can be addressed there.

**Comment by esauser** [comment]
Another scenario is if an exception occurs within the plugin, but before the plugin even executes (so a try catch can't capture and manually handle it).  The process should not be returning a zero exit code and there is nothing I can do to change it.
![image](https://user-images.githubusercontent.com/24945592/50528994-57369a80-0ab7-11e9-934c-a827989cd5fc.png)

**Comment by IVNSTN** [comment]
Setting the exit code manually seems an inconsistent solution. A plugin reported a linting error to the linter. Linting failed. Why would it report success?
IReporter receives error reports, counts statistics, knows precise number of errors and warning, and the app ignores all this.

I faced this while integrating this linter into CI pipeline. If a plugin only found any issues then the exit code is 0 (success), reading the log is uncomfortable since there are always lines about plugins loaded and files linter.

**Comment by esauser** [comment]
Why is this being marked stale?
