### ISSUE TITLE
Sql Lint for Missing-Where clause?

### ISSUE THREAD

**Issue by moopmonster** [tsqllint/tsqllint#227]
Hi, 

Is it possible for tsqllint to catch statements that are missing a where clause from a statement, especially in a DELETE/UPDATE? 

Thanks.

**Comment by nathan-boyd** [comment]
Thats definitely possible. Adding it as a plugin would be a quick way to add it to your workflow.

**Comment by janszedc** [comment]
I am attempting to create this plugin as I would like it as well, but am having issues inheriting from TSqlFragment class in my plugin dll.  I have added the dependency for the ScriptDom, but whenever I add the inheritance I noticed that TSQLLint produces the error "TSQLLint encountered a problem" when trying to --print the plugins.  In the sample plugin you use a streamreader to find any tabs and report the violation, but can you please advise how we are suppose to implement an instance of a class from the ScriptDom so that we can use it in our plugin development similarly to how the other rules were built?
